### ISSUE TITLE
Updating for Foundation for Emails 2

### ISSUE THREAD

**Issue by huebs** [thampe/ZurbInkBundle#10]
Regarding the [recent announcement](http://zurb.com/article/1420/foundation-for-emails-2-making-html-email) that a private release of ~~Ink~~ Foundation for Emails 2 will be starting soon, I was wondering if you planned to update your Bundle.  If yes, I'd love to help.  If you're not interested or don't have the time to devote to it next year, I'll plan take a pass at it myself.

I've taken a look at the [Foundation for Emails 2 Template Samples](https://github.com/zurb/foundation-emails-template) which utilizes gulp to build emails from mustache templates using [Panini](https://github.com/zurb/panini), Zurb's recently released static site generator.  The compiled templates produce markup in a custom language called "Inky" which gets transformed into email-ready HTML by the [Inky Gulp Plugin](https://github.com/zurb/gulp-inky) using the [Inky Parser](https://github.com/zurb/inky-parse).

I see no reason to utilize Panini. It's basically just a mustache engine with [a few helpers](https://github.com/zurb/panini/tree/master/helpers) that would be trivial to implement in Twig (if they aren't already [built-in](https://github.com/zurb/panini/blob/master/helpers/ifEqual.js)).  The Sass compilation is covered by Assetic and inlining is already handled by [CssToInlineStyles](https://github.com/tijsverkoyen/CssToInlineStyles).

The missing piece is Inky.  It's currently written in [555 lines of Javascript](https://github.com/zurb/inky-parse/blob/master/index.js) but there's probably a newer version coming in the private release.  My initial thought is that porting it to PHP makes the most sense for integration into Symfony.

Thanks for making this by the way.  You've saved me countless hours.  Cheers!

**Comment by thampe** [comment]
Hi,

thank you for making me aware of this. I have created a new branch ``feature/foundation-for-emails-2`` for the development and would appreciate your help ;).

**Comment by rasanga** [comment]
Is it in beta?

**Comment by thampe** [comment]
As far as I know Version 2 is still in private beta and I have no invite, yet.

**Comment by kzsolt1984** [comment]
It's now released :)

**Comment by thampe** [comment]
HI,

a new bundle version (2.1.0.0) is now released, with "Foundation for Emails 2" (2.1) Support.

**Comment by huebs** [comment]
@thampe This looks awesome!
