### ISSUE TITLE
Connection Reseting

### ISSUE THREAD

**Issue by robdonn** [thampe/ZurbInkBundle#12]
For some reason the zurb_ink_styles.add() is causing a crash. When I comment it out, the basic email renders fine with no styles but with it, I get ERR_CONNECTION_RESET.

Any ideas what could be causing this?

**Comment by robdonn** [comment]
Investigating further, it run's fine using Symfony's built-in server, but in a WAMP environment it doesn't.

Ah well...

**Comment by PastisD** [comment]
A solution : http://www.codexpedia.com/apache-server/parent-child-process-exited-with-status-3221225725-restarting-on-xamp-apache/ :)

**Comment by christophermiles** [comment]
I am having this issue using MAMP ("server unexpectedly dropped the connection") but the solution posted above by @PastisD is no help to me, as my httpd.conf does not contain a `ThreadStackSize` option
