### ISSUE TITLE
valign attribute not parsed

### ISSUE THREAD

**Issue by quantix-studio** [thampe/ZurbInkBundle#13]
Hi,
using \<columns valign="top"\> sytntax, the attribute 'valign' is not reported on dist, although it's a functionnality supported by the last releases of Inky.

That valign property is essential for outlook clients support, for instance.

Is there any way it's gonna be implemented in the bundle ?

**Comment by thampe** [comment]
Hi,

this is fixed in the latest [inky](https://github.com/thampe/inky) release (1.3.6.0). Just update to the latest version and everything should be fine ;).
