### ISSUE TITLE
Usage of ZurbInkBundle on framework other than Symfony (Laravel)

### ISSUE THREAD

**Issue by bs-thomas** [thampe/ZurbInkBundle#18]
I'm trying to see the possibilities of usage of this bundle on Laravel, together with TwigBridge, or simply just using it in general on any framework.  I would like to make use of features such as the CSS Inliner, and and Inky parser, while taking advantage of Twig's cache & data merging feature.

I don't find any tutorials other than including it from the Symfony bundle at the moment.  I was wondering if there is such documentation.

Thanks!

**Comment by thampe** [comment]
Hi,

this bundle is only designed for symfony. However all components are available as separate libraries:

* CSS Inliner: https://github.com/tijsverkoyen/CssToInlineStyles
* Inky: https://github.com/thampe/inky
* Foundation For Emails: https://github.com/zurb/foundation-emails

All provide some basic Documentation on how to use them. 

For a possible way to integrate these with Twig, have a look at the official [documentation](http://twig.sensiolabs.org/doc/advanced.html#creating-an-extension) and my implementation for the css-inliner and the inky-parser: https://github.com/thampe/ZurbInkBundle/tree/master/Twig
