### ISSUE TITLE
Compatibility with symfony 3.2.x/3.3.x

### ISSUE THREAD

**Issue by stefankaifer** [thampe/ZurbInkBundle#28]
Hi

can you change the composer.json to raise the symfony compatibility, please?

current:
 "symfony/framework-bundle": "^2.0.0 || ^3.0.0",

new:
"symfony/framework-bundle": "^2.0 || ^3.0",

I'm using 3.2.x and the ZurbInkBundle works with it, but I had to change the above row in the composer.json!

Regards

Stefan

**Comment by thampe** [comment]
Hi, 

there is a new release (`2.2.5`) which supports symfony 3.2.x.

**Comment by stefankaifer** [comment]
thanks a lot!
