### ISSUE TITLE
new stable release 

### ISSUE THREAD

**Issue by eventhorizonpl** [thampe/ZurbInkBundle#6]
Hi,

Is it possible to get new stable release in the near future?

Best regards,
Michal

**Comment by thampe** [comment]
Hi Michal,

is there anything missing or wrong?

**Comment by eventhorizonpl** [comment]
I was asking for a new stable release, because right now in project we need to block this bundle on certain commit
        "hampe/zurb-ink-bundle": "dev-master#3dc9f659d11f5d1003f2c89c3c30afbd6df0bcd2",
We need latest master, because it fixes dependency problem https://github.com/thampe/ZurbInkBundle/commit/3dc9f659d11f5d1003f2c89c3c30afbd6df0bcd2 with new phpcollection/phpcollection.

It would be great if you would tag a new release and update package informations on https://packagist.org/packages/hampe/zurb-ink-bundle

Best regards,
Michal

**Comment by thampe** [comment]
Hi, 

now everything should be correctly tagged and updated.

Thanks for your help,
Thomas

**Comment by eventhorizonpl** [comment]
@thampe 

Thank you!
